In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np

class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)
  def forward(self, x):
    pred = self.linear(x)
    return pred

torch.manual_seed(1)
model = LR(1, 1)
print(model)

x = torch.tensor([[1.0], [2.0]])
print(model.forward(x))
print(model.parameters())
[w, b] = model.parameters()
print(w)
print(b)

LR(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)
tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)
<generator object Module.parameters at 0x000001CE5C14CC48>
Parameter containing:
tensor([[0.5153]], requires_grad=True)
Parameter containing:
tensor([-0.4414], requires_grad=True)


In [2]:
X = torch.randn(20, 1)*10
y = X + 3*torch.randn(20, 1)
print(X)
print(y)

[w, b] = model.parameters()
def get_params():
  return (w[0][0].item(), b[0].item())

tensor([[ -6.5398],
        [-16.0948],
        [ -1.0017],
        [ -6.0919],
        [ -6.6291],
        [  8.0731],
        [  4.3914],
        [ 11.7120],
        [ 17.6743],
        [ -0.9536],
        [  1.3937],
        [-15.7850],
        [ -7.9807],
        [ -1.3162],
        [ -7.9844],
        [  3.3573],
        [  2.7533],
        [ 17.1630],
        [ -0.5614],
        [  9.1070]])
tensor([[ -6.0809],
        [-17.5219],
        [ -6.6481],
        [ -8.4215],
        [-12.0392],
        [  4.1481],
        [  5.7512],
        [ 15.1385],
        [ 18.4201],
        [ -6.2798],
        [  1.3172],
        [-18.8550],
        [ -7.6510],
        [ -3.2552],
        [ -6.6988],
        [  7.7855],
        [ -2.6073],
        [ 21.9940],
        [ -2.6733],
        [  8.5512]])


In [3]:
Xnp = X.numpy()
ynp = y.numpy()
print(Xnp)
print(ynp)

[[ -6.539809  ]
 [-16.094849  ]
 [ -1.0016718 ]
 [ -6.0918894 ]
 [ -6.6291137 ]
 [  8.073083  ]
 [  4.3914156 ]
 [ 11.7120075 ]
 [ 17.674273  ]
 [ -0.9536188 ]
 [  1.393715  ]
 [-15.785011  ]
 [ -7.9806986 ]
 [ -1.3162321 ]
 [ -7.984398  ]
 [  3.3573053 ]
 [  2.7533352 ]
 [ 17.163027  ]
 [ -0.56139666]
 [  9.107019  ]]
[[ -6.0809383]
 [-17.521885 ]
 [ -6.6480994]
 [ -8.421524 ]
 [-12.039206 ]
 [  4.1481204]
 [  5.751179 ]
 [ 15.138491 ]
 [ 18.420105 ]
 [ -6.2798214]
 [  1.3172076]
 [-18.855003 ]
 [ -7.651042 ]
 [ -3.2552476]
 [ -6.698771 ]
 [  7.7855387]
 [ -2.607268 ]
 [ 21.99398  ]
 [ -2.6732666]
 [  8.551222 ]]


In [4]:
# Xnp = [1,2,3]
# ynp = [1,2,3]

In [ ]:
plt.plot(Xnp, ynp, 'o')
plt.ylabel('y')
plt.xlabel('x')
plt.show()

In [ ]:
def plot_fit(title):
  plt.title = title
  w1, b1 = get_params()
  x1 = np.array([-30, 30])
  y1 = w1*x1 + b1
  plt.plot(x1, y1, 'r')
  plt.scatter(X, y)
  plt.ylabel('y')
  plt.xlabel('x')
  plt.show()
     
plot_fit('Initial Model')

In [ ]:
X = torch.randn(20, 1)*10
y = X + 3*torch.randn(20, 1)
Xnp = X.numpy()
ynp = y.numpy()
plt.plot(Xnp, ynp, 'o')
plt.ylabel('y')
plt.xlabel('x')
plt.show()